spring.application.name=mailsystem
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gurub2024@gmail.com
spring.mail.password=qqhzfkgmfxktknam

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true